version: "3.9"
services:
  db_mysql_veiculo:
    image: mysql
    container_name: db_mysql_veiculo
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
    networks:
      - fmba-bridge
    ports:
      - 3303:3306
    volumes:
      - db:/var/lib/mysql

  app_veiculo:
    image: fmba-backend/veiculo:1.0
    container_name: app_veiculo
    restart: on-failure
    depends_on:
      - db_mysql_veiculo
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8083:8080"
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://db_mysql_veiculo:3306/mysql?allowPublicKeyRetrieval=true&useSSL=false", 
        "spring.datasource.username" : "root", 
        "spring.datasource.password" : "root", 
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect", 
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.properties.hibernate.format_sql" : "true"  
        }'
    networks:
      - fmba-bridge

networks:
  fmba-bridge:
    driver: bridge

volumes:
  db: