version: "3.9"
services:
  db_veiculo:
    image: postgres:latest
    container_name: db_veiculo
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - fmba-bridge
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgres

  app_veiculo:
    image: fmba-backend/app_veiculo:1.0
    container_name: app_veiculo
    restart: on-failure
    depends_on:
      - db_veiculo
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_veiculo:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update      
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - fmba-bridge

networks:
  fmba-bridge:
    driver: bridge

volumes:
  db: